// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "7ab043a3b8dc077c0d4ecae065b4c884"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"c8ca07d10aeea8e65542ca8e7e1047bd": "1f8b08000000000000ff8c923f4fc3400cc5773e8575dde30ac452a5110c6563843deab9ed89fb535d8c92cabaef8ec22569822ad12db27f7e2f7ebef240a4a173d6375b75623e6f10dbb62ddaa722c4233eaed7cff8cac1a9ea0100a034baeaa96683485dedce968a7d70e84c677c53a2d103c7862d55bb8cc0fbd0ced54c7c9f75cda42b918ffc955289633123d6f82f8864b7aa217b50708a74c87f79db1f6b0eaee89c5598154456d93aa5acb8af998e215e8029baad122952bac2b88045563bcfd1d0344d9ee325c3ff8781229f141b137c4a28f22bddaf3846348b69eac20bcca61679dd99d9ed2d07f971d30c05cfe4b95a188ec5091359bd193b45f0e72c3ab4de865adf719a651abd664a0a70ee8473a71267698be0f51425f66fb6fa090000ffff38ab3d24ba020000",
		"ece76de402aaf9db879e9c6969be81ef": "1f8b08000000000000ffdc56b16edc300cddfd158492a948e2762ae0b96387001d8b0cec99f629b56555a2530485ffbd90630b9223b987e4badc72c05122f91edf93a53f0580b8b68723f5282a1047665d95e5a31dd4ed4bf46e306d591b6cf8f6e3e7f22576256e5c5e4d8d5492e5a0aca8c09502105259c6aefbc6a47d1040f0b326d760f8f148079ef3e7b8368326c3926cb01b40e0ef3900e2da50e312afcaa05de996615ab64fbe9aa15fa334548b0abec7b5967f0f7e2bd6f55c0bbbfb1042839da522a82a46dd1aace9720849f534fcbc203ea3ba38cf2d48de4aa4267b3052bb56d102e4a85926fd2548f2199e2680b0649ee481b6155770968d546d3ad5c1c4149c5392d1b4634f8a6d2e198dc16771132e49a67ebb7fa71d785de3d64d876db6ed468d3d85df096318598faff9a7b55c3717db9ad3493efc87af436b25bc91d47c3d0791c5b7964bd87d198f47d44bf59554cb4751c1a7a8d8eb0165cc9130465ecfdcf902100afbed41d8d7357289bb5eef71e6f14e679ca2644ecb95461a9a0f3e142100f73b03488d2d35b0f541f0366dd2160fbff731baf8ce3e67cff01990eea9fe03d3f86ecb28a191998c4a7c71c4dd87f3ceddbf1c3250766fb8a9f81b0000ffffdd3d78d96f0a0000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("github.com/deislabs/porter/pkg/mixin/feed/templates", "./templates")
		b.SetResolver("atom-template.xml", packr.Pointer{ForwardBox: gk, ForwardPath: "c8ca07d10aeea8e65542ca8e7e1047bd"})
		}()


	func() {
		b := packr.New("schema", "./schema")
		b.SetResolver("aws.json", packr.Pointer{ForwardBox: gk, ForwardPath: "ece76de402aaf9db879e9c6969be81ef"})
		}()

	return nil
}()
